<a href="https://colab.research.google.com/github/rumiantseva02polina08/Machine_learning/blob/main/%D0%A0%D1%83%D0%BC%D1%8F%D0%BD%D1%86%D0%B5%D0%B2%D0%B0_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'2.0.2'

1. Створити матрицю 3*3, заповнити її цілими випадковими числами від 1 до 5

In [2]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[1, 4, 2],
       [5, 4, 5],
       [2, 4, 5]])

2. Обчислити визначник матриці

In [3]:
det = np.linalg.det(matrix)
det

np.float64(-36.0)

3. Знайти добуток всіх елементів матриці

In [4]:
product = np.prod(matrix)
product

np.int64(32000)

In [5]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(32000)

4. Знайти суму всіх елементів матриці

In [6]:
sum = np.sum(matrix)
sum

np.int64(32)

5. Обчислити найбільший, найменший елемент матриці

In [7]:
max_element = np.max(matrix)
print("Найбільший елемент матриці:", max_element)

min_element = np.min(matrix)
print("Найменший елемент матриці:", min_element)

Найбільший елемент матриці: 5
Найменший елемент матриці: 1


6. Знайти середнє значення елементів матриці

In [8]:
mean = np.mean(matrix)
print("Середнє значення елементів матриці: ", mean)

Середнє значення елементів матриці:  3.5555555555555554


7. Знайти матрицю, що складена з квадратних коренів

In [9]:
sqrt_matrix = np.sqrt(matrix)
print("Матриця квадратних коренів: ")
print(sqrt_matrix)

Матриця квадратних коренів: 
[[1.         2.         1.41421356]
 [2.23606798 2.         2.23606798]
 [1.41421356 2.         2.23606798]]


8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [10]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print("Сума елементів кожного рядка: ")
print(row_sums)

Сума елементів кожного рядка: 
[[ 7]
 [14]
 [11]]


9. Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [15]:
vector = np.random.randint(0, 10, size=25)
print("Початковий вектор:")
print(vector)

#Сортуємо числа за спаданням
sorted_vector = np.sort(vector)[::-1]
print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[9 5 8 0 2 3 4 5 8 0 6 4 1 8 4 9 3 5 9 4 7 7 1 7 1]
Вектор після сортування за спаданням:
[9 9 9 8 8 8 7 7 7 6 5 5 5 4 4 4 4 3 3 2 1 1 1 0 0]


10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [16]:
from scipy import stats
#Знаходимо моду
mode = stats.mode(vector)

#Знаходимо медіану
median = np.median(vector)

#Знаходимо середнє
mean = np.mean(vector)

#Знаходимо максимальне значення
max_value = np.max(vector)

#Знаходимо мінімальне значення
min_value = np.min(vector)

print("Мода: ", mode)
print("Медіана: ", median)
print("Cереднє: ", mean)
print("Максимальне значення: ", max_value)
print("Мінімальне значення: ", min_value)

Мода:  ModeResult(mode=np.int64(4), count=np.int64(4))
Медіана:  5.0
Cереднє:  4.8
Максимальне значення:  9
Мінімальне значення:  0


11. Створити дві матриці 4*4, заповнені числами від 0 до 10. Обчислити суму, різницю, поелементний добуток, частку.

In [17]:
#Створюємо дві матриці 4*4 із випадкових цілих чисел від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[10  1  6  8]
 [ 6  4  2  3]
 [ 8  8  4  7]
 [ 6  1  9  4]]

Матриця 2:
[[ 1  9  4  6]
 [ 6  1  5  5]
 [ 1 10  1  7]
 [ 6  7  1 10]]


In [18]:
#Обчислюємо суму матриць
matrix_sum = matrix1 + matrix2

#Обчислюємо різницю матриць
matrix_diff = matrix1 - matrix2

#Обчислюємо поелементний добуток матриць
matrix_product = matrix1 * matrix2

#Обчислюємо поелементну частку матриць
#Для запобігання ділення на нуль, використовуємо np.divide з параметром where
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("\nСума матриць:")
print(matrix_sum)
print("\nРізниця матриць:")
print(matrix_diff)
print("\nПоелементний добуток матриць:")
print(matrix_product)
print("\nПоелементна частка матриць:")
print(matrix_division)


Сума матриць:
[[11 10 10 14]
 [12  5  7  8]
 [ 9 18  5 14]
 [12  8 10 14]]

Різниця матриць:
[[ 9 -8  2  2]
 [ 0  3 -3 -2]
 [ 7 -2  3  0]
 [ 0 -6  8 -6]]

Поелементний добуток матриць:
[[10  9 24 48]
 [36  4 10 15]
 [ 8 80  4 49]
 [36  7  9 40]]

Поелементна частка матриць:
[[10.          0.11111111  1.5         1.33333333]
 [ 1.          4.          0.4         0.6       ]
 [ 8.          0.8         4.          1.        ]
 [ 1.          0.14285714  9.          0.4       ]]


12. Задати вектор-рядок, що містить дійні числа 1.0-8.0. Зробити матрицю 3*3. помножити на вектор-рядок, що містить числа 0.0-2.0

In [19]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [20]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [21]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [22]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])